export type DemoLesson = {
  id: string
  title: string
  duration: string
  type: "video" | "quiz" | "reading"
}

export type DemoModule = {
  id: string
  title: string
  duration: string
  lessons: DemoLesson[]
}

export type DemoCourse = {
  id: string
  slug: string
  title: string
  instructor: string
  instructorBio: string
  duration: string
  level: string
  category: string
  enrolledStudents: number
  rating: number
  reviews: number
  thumbnail: string
  description: string
  isOfflineAvailable: boolean
  dataUsage: "Low" | "Medium" | "High"
  price: string
  estimatedTime: string
  prerequisites: string
  language: string
  subtitles: string[]
  learningOutcomes: string[]
  modules: DemoModule[]
}

export const demoCourses: DemoCourse[] = [
  {
    id: "1",
    slug: "computer-fundamentals",
    title: "Computer Fundamentals",
    instructor: "Dr. Sarah Johnson",
    instructorBio: "PhD in Computer Science with 15 years of teaching experience",
    duration: "8 weeks",
    level: "Beginner",
    category: "Computer Science",
    enrolledStudents: 245,
    rating: 4.8,
    reviews: 89,
    thumbnail: "/computer-fundamentals-course.jpg",
    description:
      "This comprehensive course covers the fundamental concepts of computer systems, including hardware components, software basics, operating systems, and basic programming concepts. Perfect for students beginning their journey in computer science.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "3-4 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English", "Hindi"],
    learningOutcomes: [
      "Understand basic computer hardware and software concepts",
      "Navigate different operating systems confidently",
      "Identify and troubleshoot common computer problems",
      "Prepare for advanced computer science courses",
    ],
    modules: [
      {
        id: "m1",
        title: "Introduction to Computers",
        duration: "45 min",
        lessons: [
          { id: "l1", title: "What is a Computer?", duration: "12 min", type: "video" },
          { id: "l2", title: "History of Computers", duration: "10 min", type: "reading" },
          { id: "l3", title: "Types of Computers", duration: "8 min", type: "video" },
          { id: "l4", title: "Quiz: Basics", duration: "15 min", type: "quiz" },
        ],
      },
      {
        id: "m2",
        title: "Hardware Components",
        duration: "60 min",
        lessons: [
          { id: "l1", title: "CPU, Memory, Storage", duration: "20 min", type: "video" },
          { id: "l2", title: "I/O Devices", duration: "15 min", type: "reading" },
          { id: "l3", title: "Quiz: Hardware", duration: "25 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "2",
    slug: "digital-marketing-basics",
    title: "Digital Marketing Basics",
    instructor: "Prof. Michael Chen",
    instructorBio: "Industry expert in digital strategies for SMBs",
    duration: "6 weeks",
    level: "Beginner",
    category: "Business",
    enrolledStudents: 189,
    rating: 4.6,
    reviews: 72,
    thumbnail: "/digital-marketing-course.png",
    description: "Master the fundamentals of digital marketing and social media strategies.",
    isOfflineAvailable: true,
    dataUsage: "Medium",
    price: "Free",
    estimatedTime: "2-3 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Understand digital channels",
      "Create basic campaigns",
      "Measure campaign performance",
    ],
    modules: [
      {
        id: "m1",
        title: "Intro to Digital Marketing",
        duration: "40 min",
        lessons: [
          { id: "l1", title: "Channels Overview", duration: "15 min", type: "video" },
          { id: "l2", title: "KPI Basics", duration: "25 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "3",
    slug: "basic-accounting",
    title: "Basic Accounting",
    instructor: "Dr. Priya Sharma",
    instructorBio: "CPA with 12+ years teaching financial accounting",
    duration: "10 weeks",
    level: "Beginner",
    category: "Finance",
    enrolledStudents: 156,
    rating: 4.7,
    reviews: 64,
    thumbnail: "/accounting-course.png",
    description: "Understand accounting principles, bookkeeping, and financial statements.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "2-3 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Read financial statements",
      "Understand debits and credits",
      "Perform basic bookkeeping",
    ],
    modules: [
      {
        id: "m1",
        title: "Accounting Basics",
        duration: "55 min",
        lessons: [
          { id: "l1", title: "Principles", duration: "20 min", type: "video" },
          { id: "l2", title: "Quiz: Basics", duration: "15 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "4",
    slug: "web-development-intro",
    title: "Web Development Intro",
    instructor: "Mr. Raj Patel",
    instructorBio: "Frontend engineer and educator",
    duration: "12 weeks",
    level: "Intermediate",
    category: "Computer Science",
    enrolledStudents: 203,
    rating: 4.9,
    reviews: 105,
    thumbnail: "/web-development-course.png",
    description: "Build your first websites using HTML, CSS, and JavaScript fundamentals.",
    isOfflineAvailable: false,
    dataUsage: "High",
    price: "Free",
    estimatedTime: "4-5 hours per week",
    prerequisites: "Basic computer knowledge",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Structure pages with HTML",
      "Style with CSS",
      "Add interactivity with JavaScript",
    ],
    modules: [
      {
        id: "m1",
        title: "HTML Basics",
        duration: "60 min",
        lessons: [
          { id: "l1", title: "Elements & Tags", duration: "25 min", type: "video" },
          { id: "l2", title: "Quiz: HTML", duration: "20 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "5",
    slug: "spoken-english-basics",
    title: "Spoken English Basics",
    instructor: "Ms. Aisha Verma",
    instructorBio: "Language instructor specializing in ESL for beginners",
    duration: "4 weeks",
    level: "Beginner",
    category: "Language",
    enrolledStudents: 178,
    rating: 4.5,
    reviews: 52,
    thumbnail: "/spoken-english-course.png",
    description: "Improve everyday English speaking, listening, and vocabulary.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "2 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English", "Hindi"],
    learningOutcomes: [
      "Practice common conversations",
      "Build core vocabulary",
      "Improve pronunciation",
    ],
    modules: [
      {
        id: "m1",
        title: "Everyday Phrases",
        duration: "35 min",
        lessons: [
          { id: "l1", title: "Greetings & Introductions", duration: "15 min", type: "video" },
          { id: "l2", title: "Numbers & Time", duration: "20 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "6",
    slug: "ielts-listening-strategies",
    title: "IELTS Listening Strategies",
    instructor: "Mr. Daniel Lee",
    instructorBio: "IELTS coach with 8+ years of experience",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Language",
    enrolledStudents: 96,
    rating: 4.4,
    reviews: 31,
    thumbnail: "/ielts-listening-course.png",
    description: "Techniques and practice for IELTS listening tests.",
    isOfflineAvailable: false,
    dataUsage: "Medium",
    price: "Free",
    estimatedTime: "2-3 hours per week",
    prerequisites: "Basic English",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Understand question types",
      "Note-taking methods",
      "Time management",
    ],
    modules: [
      {
        id: "m1",
        title: "Question Types",
        duration: "45 min",
        lessons: [
          { id: "l1", title: "Multiple Choice", duration: "20 min", type: "video" },
          { id: "l2", title: "Form Completion", duration: "25 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "7",
    slug: "calculus-i-foundations",
    title: "Calculus I Foundations",
    instructor: "Dr. Meera Nair",
    instructorBio: "Mathematics professor and curriculum designer",
    duration: "9 weeks",
    level: "Beginner",
    category: "Mathematics",
    enrolledStudents: 212,
    rating: 4.7,
    reviews: 77,
    thumbnail: "/calculus-foundations-course.png",
    description: "Limits, derivatives, and basic applications with minimal data usage.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "3 hours per week",
    prerequisites: "Algebra",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Compute derivatives",
      "Apply rate-of-change",
      "Understand limits",
    ],
    modules: [
      {
        id: "m1",
        title: "Limits",
        duration: "50 min",
        lessons: [
          { id: "l1", title: "Definition & Intuition", duration: "20 min", type: "video" },
          { id: "l2", title: "Exercises", duration: "30 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "8",
    slug: "linear-algebra-for-data-science",
    title: "Linear Algebra for Data Science",
    instructor: "Prof. Sameer Kulkarni",
    instructorBio: "Applied mathematician focusing on ML foundations",
    duration: "10 weeks",
    level: "Intermediate",
    category: "Mathematics",
    enrolledStudents: 134,
    rating: 4.6,
    reviews: 58,
    thumbnail: "/linear-algebra-course.png",
    description: "Vectors, matrices, and decompositions with practical intuition.",
    isOfflineAvailable: false,
    dataUsage: "Medium",
    price: "Free",
    estimatedTime: "3-4 hours per week",
    prerequisites: "Calculus basics",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Matrix operations",
      "Eigenvalues & eigenvectors",
      "Least squares",
    ],
    modules: [
      {
        id: "m1",
        title: "Vectors & Matrices",
        duration: "70 min",
        lessons: [
          { id: "l1", title: "Vector Spaces", duration: "30 min", type: "video" },
          { id: "l2", title: "Matrix Multiplication", duration: "40 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "9",
    slug: "electrical-circuits-essentials",
    title: "Electrical Circuits Essentials",
    instructor: "Dr. Arvind Rao",
    instructorBio: "Electrical engineer and researcher",
    duration: "8 weeks",
    level: "Beginner",
    category: "Engineering",
    enrolledStudents: 165,
    rating: 4.5,
    reviews: 61,
    thumbnail: "/circuits-course.png",
    description: "Ohm's law, circuit analysis, and basic design projects.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "2-3 hours per week",
    prerequisites: "High school physics",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Analyze DC circuits",
      "Use Kirchhoff's laws",
      "Design simple circuits",
    ],
    modules: [
      {
        id: "m1",
        title: "Ohm's Law",
        duration: "40 min",
        lessons: [
          { id: "l1", title: "Voltage, Current, Resistance", duration: "20 min", type: "video" },
          { id: "l2", title: "Practice Problems", duration: "20 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "10",
    slug: "thermodynamics-fundamentals",
    title: "Thermodynamics Fundamentals",
    instructor: "Prof. Kavita Menon",
    instructorBio: "Mechanical engineering professor",
    duration: "12 weeks",
    level: "Advanced",
    category: "Engineering",
    enrolledStudents: 88,
    rating: 4.3,
    reviews: 27,
    thumbnail: "/thermodynamics-course.png",
    description: "Laws of thermodynamics, entropy, and engineering applications.",
    isOfflineAvailable: false,
    dataUsage: "High",
    price: "Free",
    estimatedTime: "4-5 hours per week",
    prerequisites: "Calculus, Physics",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Apply first law",
      "Analyze cycles",
      "Understand entropy",
    ],
    modules: [
      {
        id: "m1",
        title: "Energy & Work",
        duration: "80 min",
        lessons: [
          { id: "l1", title: "Energy Forms", duration: "35 min", type: "video" },
          { id: "l2", title: "Problem Sets", duration: "45 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "11",
    slug: "entrepreneurship-101",
    title: "Entrepreneurship 101",
    instructor: "Ms. Ritu Kapoor",
    instructorBio: "Startup mentor and accelerator advisor",
    duration: "5 weeks",
    level: "Beginner",
    category: "Business",
    enrolledStudents: 301,
    rating: 4.6,
    reviews: 112,
    thumbnail: "/entrepreneurship-course.png",
    description: "From idea to MVP: fundamentals of starting up.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "2 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Validate ideas",
      "Build MVP",
      "Pitch basics",
    ],
    modules: [
      {
        id: "m1",
        title: "Ideation",
        duration: "30 min",
        lessons: [
          { id: "l1", title: "Problem Discovery", duration: "15 min", type: "video" },
          { id: "l2", title: "Customer Interviews", duration: "15 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "12",
    slug: "advanced-financial-modeling",
    title: "Advanced Financial Modeling",
    instructor: "Mr. Anil Gupta",
    instructorBio: "Investment analyst and trainer",
    duration: "9 weeks",
    level: "Advanced",
    category: "Finance",
    enrolledStudents: 74,
    rating: 4.5,
    reviews: 29,
    thumbnail: "/financial-modeling-course.png",
    description: "Build robust models for valuation and forecasting.",
    isOfflineAvailable: false,
    dataUsage: "Medium",
    price: "Free",
    estimatedTime: "3-4 hours per week",
    prerequisites: "Accounting basics",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Three-statement models",
      "DCF valuation",
      "Scenario analysis",
    ],
    modules: [
      {
        id: "m1",
        title: "Model Structure",
        duration: "60 min",
        lessons: [
          { id: "l1", title: "Linking Statements", duration: "30 min", type: "video" },
          { id: "l2", title: "Checks & Balances", duration: "30 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "13",
    slug: "python-for-beginners",
    title: "Python for Beginners",
    instructor: "Mr. Vivek Singh",
    instructorBio: "Software instructor and author",
    duration: "7 weeks",
    level: "Beginner",
    category: "Computer Science",
    enrolledStudents: 410,
    rating: 4.8,
    reviews: 180,
    thumbnail: "/python-beginners-course.png",
    description: "Start programming with Python using small, offline-friendly exercises.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "2-3 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English", "Hindi"],
    learningOutcomes: [
      "Write simple scripts",
      "Use data structures",
      "Handle files",
    ],
    modules: [
      {
        id: "m1",
        title: "Getting Started",
        duration: "50 min",
        lessons: [
          { id: "l1", title: "Installing Python", duration: "15 min", type: "reading" },
          { id: "l2", title: "Hello World", duration: "15 min", type: "video" },
          { id: "l3", title: "Practice Quiz", duration: "20 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "14",
    slug: "react-advanced-patterns",
    title: "React Advanced Patterns",
    instructor: "Ms. Neha Agarwal",
    instructorBio: "Frontend architect",
    duration: "6 weeks",
    level: "Advanced",
    category: "Computer Science",
    enrolledStudents: 138,
    rating: 4.7,
    reviews: 63,
    thumbnail: "/react-advanced-course.png",
    description: "Hooks, context, performance, and architectural patterns.",
    isOfflineAvailable: false,
    dataUsage: "High",
    price: "Free",
    estimatedTime: "3 hours per week",
    prerequisites: "JavaScript, React basics",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Optimize renders",
      "Reusable hooks",
      "State machines",
    ],
    modules: [
      {
        id: "m1",
        title: "Performance",
        duration: "55 min",
        lessons: [
          { id: "l1", title: "Memoization", duration: "25 min", type: "video" },
          { id: "l2", title: "Profiling", duration: "30 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "15",
    slug: "business-analytics-with-excel",
    title: "Business Analytics with Excel",
    instructor: "Mr. Harish Rao",
    instructorBio: "Data analyst and trainer",
    duration: "5 weeks",
    level: "Intermediate",
    category: "Business",
    enrolledStudents: 220,
    rating: 4.5,
    reviews: 70,
    thumbnail: "/analytics-excel-course.png",
    description: "Descriptive analytics using Excel with low data usage.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "2 hours per week",
    prerequisites: "Basic Excel",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Pivot tables",
      "Charts",
      "Dashboards",
    ],
    modules: [
      {
        id: "m1",
        title: "Pivot Tables",
        duration: "45 min",
        lessons: [
          { id: "l1", title: "Grouping & Slicers", duration: "20 min", type: "video" },
          { id: "l2", title: "Practice", duration: "25 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "16",
    slug: "spoken-hindi-for-beginners",
    title: "Spoken Hindi for Beginners",
    instructor: "Ms. Kavya Joshi",
    instructorBio: "Language coach",
    duration: "3 weeks",
    level: "Beginner",
    category: "Language",
    enrolledStudents: 98,
    rating: 4.2,
    reviews: 18,
    thumbnail: "/spoken-hindi-course.png",
    description: "Conversational Hindi for daily scenarios.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "1-2 hours per week",
    prerequisites: "None",
    language: "Hindi",
    subtitles: ["Hindi"],
    learningOutcomes: [
      "Common phrases",
      "Basic grammar",
      "Pronunciation",
    ],
    modules: [
      {
        id: "m1",
        title: "Introductions",
        duration: "25 min",
        lessons: [
          { id: "l1", title: "Self Introduction", duration: "10 min", type: "video" },
          { id: "l2", title: "Practice", duration: "15 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "17",
    slug: "probability-and-statistics",
    title: "Probability and Statistics",
    instructor: "Dr. Nitin Shah",
    instructorBio: "Statistician and educator",
    duration: "11 weeks",
    level: "Intermediate",
    category: "Mathematics",
    enrolledStudents: 145,
    rating: 4.6,
    reviews: 54,
    thumbnail: "/probability-stats-course.png",
    description: "Core probability and inference with practical examples.",
    isOfflineAvailable: false,
    dataUsage: "Medium",
    price: "Free",
    estimatedTime: "3-4 hours per week",
    prerequisites: "Algebra",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Random variables",
      "Distributions",
      "Hypothesis testing",
    ],
    modules: [
      {
        id: "m1",
        title: "Random Variables",
        duration: "65 min",
        lessons: [
          { id: "l1", title: "Discrete vs Continuous", duration: "30 min", type: "video" },
          { id: "l2", title: "Exercises", duration: "35 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "18",
    slug: "structural-engineering-basics",
    title: "Structural Engineering Basics",
    instructor: "Prof. Rakesh Jain",
    instructorBio: "Civil engineering department",
    duration: "9 weeks",
    level: "Intermediate",
    category: "Engineering",
    enrolledStudents: 110,
    rating: 4.4,
    reviews: 40,
    thumbnail: "/structural-engineering-course.png",
    description: "Forces, materials, and stability for structures.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "3 hours per week",
    prerequisites: "Physics, Calculus",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Stress & strain",
      "Beams & trusses",
      "Safety factors",
    ],
    modules: [
      {
        id: "m1",
        title: "Forces",
        duration: "55 min",
        lessons: [
          { id: "l1", title: "Equilibrium", duration: "25 min", type: "video" },
          { id: "l2", title: "Practice Problems", duration: "30 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "19",
    slug: "machine-learning-introduction",
    title: "Machine Learning Introduction",
    instructor: "Dr. Ananya Bose",
    instructorBio: "ML researcher",
    duration: "8 weeks",
    level: "Beginner",
    category: "Computer Science",
    enrolledStudents: 260,
    rating: 4.6,
    reviews: 95,
    thumbnail: "/ml-intro-course.png",
    description: "Supervised learning concepts with offline-friendly readings.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "3 hours per week",
    prerequisites: "Basic Python",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Regression",
      "Classification",
      "Model evaluation",
    ],
    modules: [
      {
        id: "m1",
        title: "Supervised Learning",
        duration: "60 min",
        lessons: [
          { id: "l1", title: "Linear Regression", duration: "30 min", type: "reading" },
          { id: "l2", title: "KNN", duration: "30 min", type: "video" },
        ],
      },
    ],
  },
  {
    id: "20",
    slug: "corporate-finance-essentials",
    title: "Corporate Finance Essentials",
    instructor: "Ms. Pooja Iyer",
    instructorBio: "Corporate finance professional",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Finance",
    enrolledStudents: 140,
    rating: 4.5,
    reviews: 50,
    thumbnail: "/corporate-finance-course.png",
    description: "Time value of money, capital budgeting, and risk.",
    isOfflineAvailable: false,
    dataUsage: "Medium",
    price: "Free",
    estimatedTime: "2-3 hours per week",
    prerequisites: "Basic accounting",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "NPV & IRR",
      "WACC",
      "Project selection",
    ],
    modules: [
      {
        id: "m1",
        title: "Time Value of Money",
        duration: "45 min",
        lessons: [
          { id: "l1", title: "Discounting & Compounding", duration: "20 min", type: "video" },
          { id: "l2", title: "Exercises", duration: "25 min", type: "quiz" },
        ],
      },
    ],
  },
  {
    id: "21",
    slug: "business-communication",
    title: "Business Communication",
    instructor: "Mr. Aditya Malhotra",
    instructorBio: "Corporate trainer",
    duration: "4 weeks",
    level: "Beginner",
    category: "Business",
    enrolledStudents: 195,
    rating: 4.3,
    reviews: 33,
    thumbnail: "/business-communication-course.png",
    description: "Professional writing, email, and presentation basics.",
    isOfflineAvailable: true,
    dataUsage: "Low",
    price: "Free",
    estimatedTime: "1-2 hours per week",
    prerequisites: "None",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Email etiquette",
      "Reports",
      "Presentations",
    ],
    modules: [
      {
        id: "m1",
        title: "Emails",
        duration: "30 min",
        lessons: [
          { id: "l1", title: "Structure & Tone", duration: "15 min", type: "video" },
          { id: "l2", title: "Samples", duration: "15 min", type: "reading" },
        ],
      },
    ],
  },
  {
    id: "22",
    slug: "data-structures-and-algorithms",
    title: "Data Structures and Algorithms",
    instructor: "Ms. Shreya Kulkarni",
    instructorBio: "Software engineer",
    duration: "12 weeks",
    level: "Advanced",
    category: "Computer Science",
    enrolledStudents: 180,
    rating: 4.7,
    reviews: 70,
    thumbnail: "/dsa-course.png",
    description: "Advanced DS&A with problem sets.",
    isOfflineAvailable: false,
    dataUsage: "High",
    price: "Free",
    estimatedTime: "4-5 hours per week",
    prerequisites: "Programming basics",
    language: "English",
    subtitles: ["English"],
    learningOutcomes: [
      "Trees & graphs",
      "Dynamic programming",
      "Complexity",
    ],
    modules: [
      {
        id: "m1",
        title: "Graphs",
        duration: "75 min",
        lessons: [
          { id: "l1", title: "BFS & DFS", duration: "35 min", type: "video" },
          { id: "l2", title: "Practice", duration: "40 min", type: "quiz" },
        ],
      },
    ],
  },
]

export function listDemoCourses(): DemoCourse[] {
  return demoCourses
}

export function getDemoCourseById(id: string): DemoCourse | undefined {
  return demoCourses.find((c) => c.id === id)
}

export function getDemoCourseBySlug(slug: string): DemoCourse | undefined {
  return demoCourses.find((c) => c.slug === slug)
}


